import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import YAML from "yaml";
import { loadJob, pageName, resolvePages, setSkipped, variants, writeJobFile } from "../src/batch/job.js";
import { DEFAULT_EXCLUDES, isLoginRedirect, matchesAnyGlob, normalizeUrl, urlPattern } from "../src/core/urls.js";

describe("urls", () => {
  it("normalizes for de-duplication", () => {
    expect(normalizeUrl("https://a.com/x/?b=2&utm_source=m&a=1#top")).toBe("https://a.com/x?a=1&b=2");
    expect(normalizeUrl("/p", "https://a.com/base/")).toBe("https://a.com/p");
    expect(normalizeUrl("mailto:a@b.c")).toBeUndefined();
    expect(normalizeUrl("javascript:void(0)")).toBeUndefined();
  });

  it("groups id-like segments into patterns", () => {
    expect(urlPattern("https://a.com/users/42/edit")).toBe("https://a.com/users/:id/edit");
    expect(urlPattern("https://a.com/o/3f2b8c1e-1d2a-4b5c-9e8f-0a1b2c3d4e5f")).toBe("https://a.com/o/:uuid");
    expect(urlPattern("https://a.com/list?page=2&sort=x")).toBe("https://a.com/list?page=&sort=");
    expect(urlPattern("https://a.com/blog/hello-world")).toBe("https://a.com/blog/hello-world");
  });

  it("never follows destructive links by default", () => {
    expect(matchesAnyGlob("https://a.com/account/logout", DEFAULT_EXCLUDES)).toBe(true);
    expect(matchesAnyGlob("https://a.com/items/3/delete?x=1", DEFAULT_EXCLUDES)).toBe(true);
    expect(matchesAnyGlob("https://a.com/files/report.pdf", DEFAULT_EXCLUDES)).toBe(true);
    expect(matchesAnyGlob("https://a.com/users", DEFAULT_EXCLUDES)).toBe(false);
    expect(matchesAnyGlob("https://a.com/admin/users/3", ["/admin/**"])).toBe(true);
  });

  it("detects login redirects", () => {
    expect(isLoginRedirect("https://a.com/dash", "https://a.com/login?next=/dash")).toBe(true);
    expect(isLoginRedirect("https://a.com/dash", "https://accounts.google.com/o/oauth2")).toBe(true);
    expect(isLoginRedirect("https://a.com/login", "https://a.com/login")).toBe(false);
    expect(isLoginRedirect("https://a.com/dash", "https://a.com/dash")).toBe(false);
    expect(isLoginRedirect("https://a.com/dash", "https://a.com/gate", "/gate")).toBe(true);
    expect(isLoginRedirect("https://a.com/dash", "https://a.com/Gate", "/\\/gate/i")).toBe(true);
  });
});

describe("job", () => {
  it("expands the matrix", () => {
    expect(variants().map((v) => v.id)).toEqual(["capture"]);
    expect(variants({ viewport: ["1440x900", "390x844m"], theme: ["light", "dark"] }).map((v) => v.id)).toEqual([
      "1440x900.light",
      "1440x900.dark",
      "390x844m.light",
      "390x844m.dark",
    ]);
    expect(variants({ dpr: [1, "2x"] })[1]!.patch).toEqual({ dpr: 2 });
  });

  it("resolves pages against base with unique names", () => {
    const pages = resolvePages({
      base: "https://a.com/app/",
      wait: { delay: 100 },
      pages: ["./", "users", "/other", { url: "users", wait: { selector: ".x" } }, { url: "gone", skip: true }],
    });
    expect(pages.map((p) => [p.url, p.name])).toEqual([
      ["https://a.com/app/", "index"],
      ["https://a.com/app/users", "users"],
      ["https://a.com/other", "other"],
      ["https://a.com/app/users", "users-2"],
    ]);
    expect(pages[3]!.wait).toEqual({ delay: 100, selector: ".x" });
    expect(pageName("https://a.com/s?q=a b")).toBe("s--q-a-b");
  });

  it("writes an editable job file and toggles skip without losing comments", () => {
    const path = join(mkdtempSync(join(tmpdir(), "pagestill-job-")), "pages.yaml");
    writeJobFile(path, {
      header: " Generated by test",
      base: "https://a.com/",
      entries: [
        { url: "https://a.com/", note: "Home" },
        { url: "https://a.com/users/1", comment: " /users/:id — 3 found", note: "User 1" },
        { url: "https://b.com/x", skip: true },
      ],
    });
    const text = readFileSync(path, "utf8");
    expect(text).toContain("# Generated by test");
    expect(text).toContain("# /users/:id — 3 found");
    expect(loadJob(path).pages).toEqual(["/", "/users/1", { url: "https://b.com/x", skip: true }]);

    const doc = YAML.parseDocument(text);
    setSkipped(doc, 1, true);
    setSkipped(doc, 2, false);
    const after = doc.toString();
    expect(after).toContain("# /users/:id — 3 found");
    expect(YAML.parse(after).pages).toEqual(["/", { url: "/users/1", skip: true }, "https://b.com/x"]);
    expect(after).toContain("- url: /users/1 # User 1");

    const back = YAML.parseDocument(after);
    setSkipped(back, 1, false);
    expect(back.toString()).toContain("- /users/1 # User 1");
  });
});
